# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5256ebdc734b88b5cce78cea51dd8b9dde2de768028971c3124a9ede3901e8fde39623918d5144b2b7f87d09ca6557fca832fc305ca317e87069a966534c9e30

test:
  secret_key_base: 357dbd5105c98dc6cfbe9d9a6a3128ed937ebd0f315828a9e0f3ee6b7263cade95cde43cfc28be6a1bac9baefb42378e65a7bffe8c40afa3b03274f6ff050341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
